"""
错误码常量定义
根据开发方案第 17 节：统一管理所有错误码，便于前端识别和处理
"""


class ErrorCode:
    """错误码常量类"""
    
    # ==================== 通用错误 ====================
    SUCCESS = "SUCCESS"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    
    # ==================== 认证相关 ====================
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_PASSWORD_INCORRECT = "AUTH_PASSWORD_INCORRECT"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    AUTH_USER_DISABLED = "AUTH_USER_DISABLED"
    AUTH_ADMIN_PERMISSION_DENIED = "AUTH_ADMIN_PERMISSION_DENIED"
    
    # ==================== 邮件验证码相关 ====================
    # 根据注册登录与权限设计方案第 8.1 节定义
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"  # 邮箱已注册（注册时）
    EMAIL_NOT_REGISTERED = "EMAIL_NOT_REGISTERED"  # 邮箱未注册（登录时）
    INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE"  # 验证码错误或已过期
    SEND_CODE_TOO_FREQUENT = "SEND_CODE_TOO_FREQUENT"  # 发送验证码过于频繁（60秒内）
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED"  # 邮件发送失败
    
    # ==================== 用量与订阅限制 ====================
    USAGE_ANALYSIS_LIMIT_EXCEEDED = "USAGE_ANALYSIS_LIMIT_EXCEEDED"
    USAGE_GENERATION_LIMIT_EXCEEDED = "USAGE_GENERATION_LIMIT_EXCEEDED"
    SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED"
    SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND"
    
    # ==================== 上传与图片处理 ====================
    UPLOAD_FILE_TOO_LARGE = "UPLOAD_FILE_TOO_LARGE"
    UPLOAD_INVALID_FORMAT = "UPLOAD_INVALID_FORMAT"
    UPLOAD_FAILED = "UPLOAD_FAILED"
    IMAGE_PROCESSING_FAILED = "IMAGE_PROCESSING_FAILED"
    
    # ==================== 分析任务相关 ====================
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_ALREADY_COMPLETED = "TASK_ALREADY_COMPLETED"
    TASK_PROCESSING = "TASK_PROCESSING"
    TASK_FAILED = "TASK_FAILED"
    FEASIBILITY_CHECK_FAILED = "FEASIBILITY_CHECK_FAILED"
    
    # ==================== Gemini API 相关 ====================
    GEMINI_CALL_FAILED = "GEMINI_CALL_FAILED"
    GEMINI_TIMEOUT = "GEMINI_TIMEOUT"
    GEMINI_INVALID_RESPONSE = "GEMINI_INVALID_RESPONSE"
    GEMINI_QUOTA_EXCEEDED = "GEMINI_QUOTA_EXCEEDED"
    
    # ==================== 导出相关 ====================
    EXPORT_FAILED = "EXPORT_FAILED"
    EXPORT_FORMAT_NOT_SUPPORTED = "EXPORT_FORMAT_NOT_SUPPORTED"
    EXPORT_TASK_NOT_COMPLETED = "EXPORT_TASK_NOT_COMPLETED"
    
    # ==================== 支付相关 ====================
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_METHOD_NOT_SUPPORTED = "PAYMENT_METHOD_NOT_SUPPORTED"
    REFUND_FAILED = "REFUND_FAILED"
    
    # ==================== 数据验证相关 ====================
    VALIDATION_FAILED = "VALIDATION_FAILED"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_FIELD_FORMAT = "INVALID_FIELD_FORMAT"


# 错误码到 HTTP 状态码的映射
ERROR_CODE_TO_HTTP_STATUS = {
    ErrorCode.SUCCESS: 200,
    ErrorCode.INTERNAL_ERROR: 500,
    ErrorCode.INVALID_REQUEST: 400,
    ErrorCode.UNAUTHORIZED: 401,
    ErrorCode.FORBIDDEN: 403,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.AUTH_TOKEN_INVALID: 401,
    ErrorCode.AUTH_TOKEN_EXPIRED: 401,
    ErrorCode.AUTH_LOGIN_FAILED: 401,
    ErrorCode.AUTH_PASSWORD_INCORRECT: 401,
    ErrorCode.AUTH_USER_NOT_FOUND: 404,
    ErrorCode.AUTH_USER_DISABLED: 403,
    ErrorCode.AUTH_ADMIN_PERMISSION_DENIED: 403,
    ErrorCode.EMAIL_ALREADY_REGISTERED: 400,
    ErrorCode.EMAIL_NOT_REGISTERED: 400,
    ErrorCode.INVALID_VERIFICATION_CODE: 400,
    ErrorCode.SEND_CODE_TOO_FREQUENT: 429,
    ErrorCode.EMAIL_SEND_FAILED: 500,
    ErrorCode.USAGE_ANALYSIS_LIMIT_EXCEEDED: 403,
    ErrorCode.USAGE_GENERATION_LIMIT_EXCEEDED: 403,
    ErrorCode.SUBSCRIPTION_EXPIRED: 403,
    ErrorCode.SUBSCRIPTION_NOT_FOUND: 404,
    ErrorCode.UPLOAD_FILE_TOO_LARGE: 400,
    ErrorCode.UPLOAD_INVALID_FORMAT: 400,
    ErrorCode.UPLOAD_FAILED: 500,
    ErrorCode.IMAGE_PROCESSING_FAILED: 500,
    ErrorCode.TASK_NOT_FOUND: 404,
    ErrorCode.TASK_ALREADY_COMPLETED: 400,
    ErrorCode.TASK_PROCESSING: 202,
    ErrorCode.TASK_FAILED: 500,
    ErrorCode.FEASIBILITY_CHECK_FAILED: 500,
    ErrorCode.GEMINI_CALL_FAILED: 500,
    ErrorCode.GEMINI_TIMEOUT: 504,
    ErrorCode.GEMINI_INVALID_RESPONSE: 500,
    ErrorCode.GEMINI_QUOTA_EXCEEDED: 429,
    ErrorCode.EXPORT_FAILED: 500,
    ErrorCode.EXPORT_FORMAT_NOT_SUPPORTED: 400,
    ErrorCode.EXPORT_TASK_NOT_COMPLETED: 400,
    ErrorCode.PAYMENT_FAILED: 500,
    ErrorCode.PAYMENT_METHOD_NOT_SUPPORTED: 400,
    ErrorCode.REFUND_FAILED: 500,
    ErrorCode.VALIDATION_FAILED: 400,
    ErrorCode.MISSING_REQUIRED_FIELD: 400,
    ErrorCode.INVALID_FIELD_FORMAT: 400,
}


def get_http_status(error_code: str) -> int:
    """
    根据错误码获取对应的 HTTP 状态码
    
    Args:
        error_code: 错误码字符串
        
    Returns:
        HTTP 状态码（默认 500）
    """
    return ERROR_CODE_TO_HTTP_STATUS.get(error_code, 500)

