import React, { createContext, useContext, useState, useEffect } from 'react';
import { AnimatePresence } from 'motion/react';
import { LanguageTransition } from '../../components/transitions/LanguageTransition';

type Language = 'en' | 'zh';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  en: {
    // General
    'app.title': 'STYLECLONE',
    'app.subtitle': 'Quantum Lens V5.0',
    'loading': 'LOADING...',
    
    // Landing
    'landing.digital': 'DIGITAL',
    'landing.darkroom': 'DARKROOM',
    'landing.description': "Color grading, redefined. We decode aesthetic DNA into precise parameters. From inspiration to masterpiece, instantly. Never been simpler.",
    'landing.enter_system': 'INITIALIZE SYSTEM',
    'landing.view_demo': 'View Demo',
    'landing.feature.ai_color.title': 'AI Color Grading',
    'landing.feature.ai_color.desc': 'Neural networks analyze reference images to extract and apply complex color DNA to your photos instantly.',
    'landing.feature.style_cloning.title': 'Style Cloning',
    'landing.feature.style_cloning.desc': 'Proprietary Quantum Lens technology separates style from content, allowing for perfect aesthetic replication.',
    'landing.feature.comp_analysis.title': 'Composition Analysis',
    'landing.feature.comp_analysis.desc': 'Deep learning algorithms break down visual structure, guiding you to perfect framing and balance.',
    'landing.access_levels': 'ACCESS LEVELS',
    'landing.select_tier': 'SELECT YOUR CLEARANCE TIER',
    'landing.recommended': 'Recommended',
    'landing.select_plan': 'Select Plan',
    'landing.footer': '© 2025 PHOTOSCIENCE INC. ALL SYSTEMS OPERATIONAL.',
    
    // Pricing
    'pricing.trainee.title': 'TRAINEE',
    'pricing.trainee.price': 'Free',
    'pricing.trainee.f1': 'Basic Color Analysis',
    'pricing.trainee.f2': '5 Daily Scans',
    'pricing.trainee.f3': 'Standard Speed',
    'pricing.trainee.f4': 'Community Access',
    'pricing.pro.title': 'PRO LICENSE',
    'pricing.pro.price': '¥98',
    'pricing.pro.period': '/mo',
    'pricing.pro.f1': 'Unlimited Scans',
    'pricing.pro.f2': 'Advanced Vectorscope',
    'pricing.pro.f3': '4K Export Support',
    'pricing.pro.f4': 'Priority Processing',
    'pricing.pro.f5': 'Style History',
    'pricing.studio.title': 'STUDIO',
    'pricing.studio.price': '¥298',
    'pricing.studio.period': '/mo',
    'pricing.studio.f1': 'API Access',
    'pricing.studio.f2': 'Team Collaboration',
    'pricing.studio.f3': 'Custom Neural Models',
    'pricing.studio.f4': 'Raw File Support',
    'pricing.studio.f5': 'Dedicated Support',

    
    // Auth
    'auth.login': 'LOG IN',
    'auth.register': 'REQUEST ACCESS',
    'auth.verify_identity': 'IDENTITY VERIFICATION',
    'auth.new_operator': 'NEW OPERATOR REGISTRATION',
    'auth.email_addr': 'EMAIL ADDRESS',
    'auth.mobile_num': 'MOBILE NUMBER',
    'auth.password': 'PASSWORD',
    'auth.confirm_password': 'CONFIRM PASSWORD',
    'auth.get_code': 'GET CODE',
    'auth.use_code': 'Use Verification Code',
    'auth.use_pass': 'Use Password',
    'auth.access_system': 'ACCESS SYSTEM',
    'auth.establish_id': 'ESTABLISH ID',
    'auth.protocol_v5': 'SECURE CONNECTION PROTOCOL v5.0',
    'auth.email_code': 'Email Code',
    'auth.sms_code': 'SMS Code',
    'auth.verifying': 'VERIFYING CREDENTIALS...',
    'auth.no_account': "Don't have a clearance code?",
    'auth.has_account': "Already have an identity?",

    // Modals - Common
    'modal.common.exposure': 'Exposure',
    'modal.common.contrast': 'Contrast',
    'modal.common.highlights': 'Highlights',
    'modal.common.shadows': 'Shadows',
    'modal.common.whites': 'Whites',
    'modal.common.blacks': 'Blacks',
    'modal.common.texture': 'Texture',
    'modal.common.clarity': 'Clarity',
    'modal.common.dehaze': 'Dehaze',
    'modal.common.vibrance': 'Vibrance',
    'modal.common.saturation': 'Saturation',
    'modal.common.temp': 'Temp',
    'modal.common.tint': 'Tint',
    'modal.common.midtones': 'Midtones',
    'modal.color.reds': 'Reds',
    'modal.color.yellows': 'Yellows',
    'modal.color.greens': 'Greens',
    'modal.color.cyans': 'Cyans',
    'modal.color.blues': 'Blues',
    'modal.color.magentas': 'Magentas',
    'modal.color.neutrals': 'Neutrals',
    'modal.common.cyan': 'Cyan',
    'modal.common.magenta': 'Magenta',
    'modal.common.yellow': 'Yellow',
    'modal.common.black': 'Black',
    
    // Simulation Stage
    'simulation.rendering': 'RENDERING...',
    'simulation.ai_result': 'AI Generated Result',
    'simulation.quantum_grade': 'Quantum Grade Applied',
    'simulation.diff_heatmap': 'DIFFERENCE HEATMAP',
    'simulation.match_score': 'MATCH SCORE',
    'simulation.ref_dna': 'REFERENCE DNA',
    'simulation.source_input': 'SOURCE STYLE INPUT',
    'simulation.synth_clone': 'SYNTHESIZED CLONE',
    'simulation.final_output': 'FINAL OUTPUT',
    'simulation.active_params': 'Active Parameters',
    'simulation.ai_confidence': 'AI Confidence',
    'simulation.param.warmth': 'WARMTH',
    'simulation.param.tint': 'TINT',
    'simulation.param.shadow': 'SHADOW',
    'simulation.param.highlight': 'HIGHLIGHT',
    'simulation.download_preset': 'Download Preset',
    'simulation.download_lut': 'Download LUT',
    'simulation.desc_xmp': 'Universal XML format compatible with Adobe Lightroom & Camera Raw.',
    'simulation.desc_lut': '33-Point 3D LUT for video grading (DaVinci, Premiere, FCPX).',
    'simulation.secure_channel': 'SECURE_CHANNEL_ESTABLISHED',
    'simulation.version': 'VERSION 2.4.0_BUILD_88',

    // Modals - Color
    'modal.color.title': 'SPECTRAL GRADING',
    'modal.color.strategy': '/// COLOR STRATEGY',
    'modal.color.cinematic': 'CINEMATIC GRADING',
    'modal.color.hsl': 'HOLOGRAPHIC HSL MATRIX',
    'modal.color.wb': 'WHITE BALANCE',
    'modal.color.wb_target': 'WHITE BALANCE TARGET',
    'modal.color.tint_cor': 'Tint Correction',
    'modal.color.grading_vectors': 'Grading Vectors',
    'modal.color.balance': 'Balance',
    'modal.color.spectrum': 'Spectrum Matrix',

    // Modals - Lightroom
    'modal.lr.title': 'LIGHTROOM DEVELOP',
    'modal.lr.protocol': 'COLOR MATCH PROTOCOL',
    'modal.lr.brief': 'MISSION KEY POINTS',
    'modal.lr.signal': 'Signal Monitor',
    'modal.lr.rgb_parade': 'RGB PARADE / WAVEFORM',
    'modal.lr.basic': 'Basic Correction',
    'modal.lr.curve': 'Tone Curve',
    'modal.lr.comp': 'Composition Analysis',
    'modal.lr.hsl_mixer': 'HSL / Color Mixer',
    'modal.lr.grading': 'Color Grading',
    'modal.lr.exp_dr': 'Exposure & Dynamic Range',
    'modal.lr.presence': 'Presence & Atmosphere',

    // Modals - Photoshop
    'modal.ps.title': 'PHOTOSHOP WORKFLOW',
    'modal.ps.hist': 'Composite Histogram',
    'modal.ps.render': 'FINAL RENDER OUTPUT',
    'modal.ps.layers_active': 'LAYERS ACTIVE',
    'modal.ps.stack': 'Adjustment Stack',
    'modal.ps.cr': 'Camera Raw Filter',
    'modal.ps.levels': 'Levels',
    'modal.ps.curves': 'Curves',
    'modal.ps.sel_col': 'Selective Color',
    'modal.ps.db': 'Dodge & Burn',
    'modal.ps.atmos': 'Atmosphere & Grain',
    'modal.ps.grain': 'GRAIN SIMULATION',
    'modal.ps.vol': 'ATMOSPHERE VOLUMETRICS',
    
    // Theme Cards - Status
    'status.awaiting': 'STATUS: AWAITING DIAGNOSIS',
    'status.decrypting': 'STATUS: DECRYPTING STREAM...',
    'status.ready': 'STATUS: READY FOR SYNTHESIS',
    
    // Theme Cards - Diagnosis
    'cards.analysis_bg': 'ANALYSIS',
    'cards.diag_layer': 'DIAGNOSIS LAYER',
    'cards.ai_assess': '// AI Vision Assessment',
    'cards.review': 'REVIEW',
    'cards.composition': 'COMPOSITION',
    'cards.lighting': 'LIGHTING',
    'cards.aesthetic': 'Aesthetic Score',
    'cards.geometry': 'Geometry & Flow',
    'cards.zone': 'Zone System',
    'cards.unlock_btn': 'Generate Execution Plan',
    'cards.decrypting_vec': 'DECRYPTING SECURE VECTORS...',
    
    // Theme Cards - Execution
    'cards.exec_bg': 'EXECUTION',
    'cards.exec_layer': 'EXECUTION LAYER',
    'cards.tech_proc': '// Technical Processing',
    'cards.locked': 'LOCKED',
    'cards.color': 'COLOR',
    'cards.lightroom': 'LIGHTROOM',
    'cards.photoshop': 'PHOTOSHOP',
    'cards.spectral': 'Spectral Grading',
    'cards.raw_dev': 'Raw Development',
    'cards.retouch': 'Retouch Workflow',
    'cards.init_sim': 'Initialize Simulation',
    'cards.decrypted_msg': 'EXECUTION VECTORS DECRYPTED',
    
    // Photo Upload Zone
    'upload.wavelength': 'WAVELENGTH',
    'upload.flux': 'SPECTRAL FLUX: DETECTED',
    
    // Main App - Header
    'nav.upload': 'UPLOAD',
    'nav.analysis': 'STYLE ANALYSIS',
    'nav.simulation': 'OPEN SIMULATION',
    'nav.unlock_sim': 'Complete AI Diagnosis to unlock Simulation',
    
    // Upload Stage
    'stage.upload.title': 'QUANTUM LENS',
    'stage.upload.subtitle': 'AI Neural Network Style Transfer System',
    'stage.upload.ref_label': 'Reference Style',
    'stage.upload.target_label': 'Target Source',
    'stage.upload.btn_analyze': 'Initialize Analysis',
    'stage.upload.btn_analyzing': 'PROCESSING TENSORS...',
    
    // Analysis Stage
    'stage.analysis.title': 'Analysis Results',
    'stage.analysis.simulate': 'Run Simulation',

    // Simulation Stage
    'simulation.title': 'SIMULATION RENDER',
    'simulation.subtitle.gen': 'GEMINI FLASH GENERATION',
    'simulation.subtitle.opt': 'REAL-TIME OPTICAL ENGINE',
    'simulation.processing': 'PROCESSING NEURAL STYLE TRANSFER...',
    'simulation.engine_ready': 'ENGINE READY',
    'simulation.gpu_accel': 'GPU ACCELERATED',
    'simulation.split_view': 'SPLIT VIEW',
    'simulation.diff_map': 'DIFFERENCE MAP',
    'simulation.style_match': 'STYLE MATCH',
    'simulation.rerun': 'RE-RUN SIMULATION',
    'simulation.download': 'DOWNLOAD ASSETS',
    'simulation.export_panel': 'DATA EXPORT CONSOLE',
    'simulation.preset_xmp': 'LIGHTROOM PRESET (.XMP)',
    'simulation.lut_cube': '3D LUT (.CUBE)',
    'simulation.generating': 'GENERATING...',
    'simulation.download_ready': 'DOWNLOAD READY',
    'simulation.close': 'CLOSE CONSOLE',
    
    // User Profile
    'profile.title': 'OPERATOR PROFILE',
    'profile.id': 'OPERATOR ID',
    'profile.clearance': 'CLEARANCE LEVEL',
    'profile.credits': 'COMPUTE CREDITS',
    'profile.history': 'OPERATION HISTORY',
    'profile.logout': 'DISCONNECT',
    'profile.operator': 'OPERATOR',
    'profile.settings_console': 'SETTINGS CONSOLE',
    'profile.change_avatar': 'CHANGE AVATAR',
    'profile.reset_key': 'RESET KEY',
    'profile.generating': 'GENERATING...',
    'profile.username': 'Username',
    'profile.email': 'Email Address',
    'profile.password': 'Password',
    'profile.update': 'Update',
    'profile.alipay_binding': 'Alipay Binding',
    'profile.secure_quick': 'Secure quick payment integration',
    'profile.connected': 'CONNECTED',
    'profile.tab_identity': 'Identity',
    'profile.tab_plan': 'Plan & Usage',
    'profile.tab_billing': 'Billing',
    'profile.tab_tasks': 'Task Log',
    'profile.tab_network': 'Network',
    'profile.tab_protocols': 'Protocols',
    
    // Subscription
    'subscription.current_plan': 'Current Plan',
    'subscription.gpu_cluster': 'HIGH VELOCITY GPU CLUSTER',
    'subscription.load': 'LOAD',
    'subscription.used_credits': 'Used Credits',
    'subscription.total_limit': 'Total Limit',
    'subscription.renewal': 'Renewal',
    'subscription.days': 'Days',
    'subscription.mo': '/mo',
    'subscription.tier_free': 'FREE',
    'subscription.tier_pro': 'PRO',
    'subscription.tier_enterprise': 'ENTERPRISE',
    'subscription.plan_selection': 'Plan Selection',
    'subscription.switching_to': 'Switching to {tier} tier...',
    
    // Share
    'share.title': 'NEURAL NETWORK SYNC',
    'share.desc': 'Enable public access to your simulation results. Contribute to the global learning model.',
    'share.auto_publish': 'AUTO-PUBLISH',
    'share.sync_enabled': 'Sync Enabled',
    'share.connected_hive': 'You are now connected to the hive.',

    // Billing & Payment
    'billing.payment_methods': 'Payment Methods',
    'billing.add_method': 'Add Payment Method',
    'billing.edit_card': 'Edit Card Details',
    'billing.card_number': 'Card Number',
    'billing.cardholder': 'Cardholder Name',
    'billing.expiry': 'Expiry Date',
    'billing.cvv': 'CVV/CVC',
    'billing.set_default': 'Set as Default',
    'billing.remove': 'Remove',
    'billing.scan_qr': 'Scan QR Code to Bind',
    'billing.connect_paypal': 'Connect PayPal Account',
    'billing.bind_success': 'Payment Method Linked Successfully',
    'billing.update_success': 'Payment Details Updated',
    'billing.no_methods': 'No payment methods configured.',
    'billing.primary': 'PRIMARY',
    'billing.scan_instruction': 'Please open your app and scan the code below.',
    'billing.simulating_redirect': 'Simulating secure gateway redirect...',
    'billing.simulating_scan': 'Waiting for payment provider confirmation...',
    'billing.tab_card': 'Credit Card',
    'billing.tab_alipay': 'Alipay/WeChat',
    'billing.tab_paypal': 'PayPal',
    'billing.exp_label': 'EXP',
    'billing.click_scan': 'Click to Simulate Scan',
    'billing.connecting': 'Connecting...',
    'billing.update_btn': 'Update Card',
    'billing.placeholder_name': 'NAME ON CARD',
    'billing.paypal_title': 'PayPal Secure Connect',
    'billing.paypal_desc': 'You will be redirected to PayPal to authorize the binding agreement.',

    // Zone System Visualizer
    'zone.system.title': 'Ansel Adams Zone System',
    'zone.system.subtitle': 'LUMINANCE MAPPING',
    'zone.face': 'FACE',
    'zone.pure_black': 'PURE BLACK',
    'zone.middle_grey': 'MIDDLE GREY',
    'zone.pure_white': 'PURE WHITE',
    'zone.desc.0': 'No detail',
    'zone.desc.1': 'Slight tonality',
    'zone.desc.2': 'Darkest texture',
    'zone.desc.3': 'Avg shadow detail',
    'zone.desc.4': 'Landscape shadow / Dark skin',
    'zone.desc.5': '18% Grey / Kodak Card',
    'zone.desc.6': 'Caucasian/Asian Skin',
    'zone.desc.7': 'Pale skin / Light stone',
    'zone.desc.8': 'Highlights with detail',
    'zone.desc.9': 'Near white',
    'zone.desc.10': 'Specular light sources',
    'zone.name.0': 'Pure Black',
    'zone.name.1': 'Near Black',
    'zone.name.2': 'Texture Black',
    'zone.name.3': 'Shadows',
    'zone.name.4': 'Dark Skin',
    'zone.name.5': 'Middle Grey',
    'zone.name.6': 'Avg Skin',
    'zone.name.7': 'Light Skin',
    'zone.name.8': 'Whites',
    'zone.name.9': 'Brilliant White',
    'zone.name.10': 'Paper White',

    // AI Analysis Panel
    'ai.monitor.title': 'Visual Cortex Monitor',
    'ai.live_signal': 'LIVE SIGNAL',
    'ai.idle_desc': 'Exposure data is live. To decode Style DNA, Color Harmony, and Composition, engage the Neural Engine.',
    'ai.btn_scan': 'Initiate Deep Scan',
    'ai.analyzing': 'Analyzing Visual Cortex',
    'ai.step.hist': 'Extracting Histogram Data...',
    'ai.step.color': 'Mapping Color Vectors...',
    'ai.step.style': 'Generating Style Embeddings...',
    'ai.step.report': 'Finalizing Report...',
    'ai.report.title': 'AI Diagnosis Report',
    'ai.token': 'TOKEN',
    'ai.tab.overview': 'Overview',
    'ai.tab.color': 'Color DNA',
    'ai.tab.lr': 'Lightroom',
    'ai.tab.ps': 'Photoshop',
    'ai.sec.style': '01. Style Profile',
    'ai.sec.comp': '02. Composition & Structure',
    'ai.sec.zone': '03. Zone System Exposure',
    'ai.sec.harmony': '04. Color Harmony Engine',
    'ai.sec.lr': '05. Lightroom Protocol',
    'ai.sec.ps': '06. Photoshop Stack',
    'ai.comp.struct': 'Structural Analysis',
    'ai.comp.weight': 'Subject Weight',
    'ai.color.grading': 'Cinematic Grading',
    'ai.color.hsl': 'Holographic HSL Matrix',
    'ai.color.wb': 'White Balance',
    'ai.color.style_key': 'Style Key',

    // Color Grade Wheel
    'color.grade.engine': 'GRADING_ENGINE',
    'color.grade.awaiting': 'Awaiting vector input. Hover wheels for split-tone logic...',
    'color.grade.pushing': 'Pushing {label} towards Hue {hue}° at {sat}% saturation.',

    // HSL Visualizer
    'hsl.matrix.title': 'Holographic Spectrum Matrix',
    'hsl.matrix.sat': 'Saturation',
    'hsl.matrix.lum': 'Luminance',
    'hsl.matrix.engine': 'COLOR_MATRIX',
    'hsl.matrix.idle': 'Select frequency band for modulation analysis...',
    'hsl.reason.no_dev': 'No significant deviation from source baseline.',
    'hsl.reason.adjust': 'Adjusting',
    'hsl.reason.match': 'to match target palette density.',
    'hsl.reason.hue': 'Hue shift',
    'hsl.reason.sat': 'Sat',
    'hsl.reason.lum': 'Lum',
    'hsl.channel.red': 'Red',
    'hsl.channel.orange': 'Orange',
    'hsl.channel.yellow': 'Yellow',
    'hsl.channel.green': 'Green',
    'hsl.channel.aqua': 'Aqua',
    'hsl.channel.blue': 'Blue',
    'hsl.channel.purple': 'Purple',
    'hsl.channel.magenta': 'Magenta',

    // Visual Analysis Dashboard
    'vad.tools': 'Analysis Tools',
    'vad.scopes': 'Professional Scopes',
    'vad.histogram': 'Luminance Histogram',
    'vad.vectorscope': 'Color Radar',
    'vad.ai_diagnosis': 'AI Diagnosis',
    'vad.overlays': 'Overlays',
    'vad.false_color_desc': 'False color maps luminance to color, helping you judge exposure without guessing.',
    'vad.show_map': 'Show Exposure Map',
    'vad.hide_map': 'Hide Exposure Map',
    'vad.luma_dist': 'Luminance Distribution (Y)',
    'vad.luma_range': '0 (Black) — 255 (White)',
    'vad.hist_desc': 'Shows the proportion of shadows (left), midtones (center), or highlights (right) in the image.',
    'vad.chroma_vec': 'Chroma Vector (UV)',
    'vad.chroma_range': 'Center=Gray, Edge=Vivid',
    'vad.vector_desc': '"Color Compass": Direction represents hue, distance from center represents saturation.',
    'vad.skin_tone': 'Skin tone should fall on the pink line.',
    'vad.skin_tone_title': 'Skin Tone Line Guide',
    'vad.skin_tone_subtitle': 'SKIN TONE LINE',
    'vad.skin_tone_location': 'Location',
    'vad.skin_tone_location_desc': '11 o\'clock direction on color radar (approx -33°)',
    'vad.skin_tone_meaning': 'Meaning',
    'vad.skin_tone_meaning_desc': 'Reference range for standard skin tone hue and saturation',
    'vad.skin_tone_guide': 'Judgment Guide',
    'vad.skin_tone_accurate': 'On line: Accurate skin tone',
    'vad.skin_tone_yellow': 'Right: Yellowish (warm color temp)',
    'vad.skin_tone_red': 'Left: Reddish (over-saturated)',
    'vad.skin_tone_green': 'Down: Greenish (cool white balance)',
  },
  zh: {
    // General
    'app.title': 'STYLECLONE',
    'app.subtitle': 'Quantum Lens V5.0',
    'loading': '加载中...',
    
    // Landing
    'landing.digital': 'DIGITAL',
    'landing.darkroom': 'DARKROOM',
    'landing.description': '我们重新定义了仿色教程。当你上传一张喜欢的照片，AI 神经网络便开始解构其美学的 DNA——从直方图的呼吸感，到色彩分级的微妙情绪。它不只提供滤镜，更将艺术家的直觉，转化为精确的参数。让那些令人惊叹的影调，在你的作品中精准重现。\n\n从视觉到数据，从灵感到杰作。专业影像，从未如此简单。',
    'landing.enter_system': '开启探索',
    'landing.view_demo': '观看视频',
    'landing.feature.ai_color.title': 'AI 色彩分级',
    'landing.feature.ai_color.desc': '神经网络分析参考图像，即时提取并应用复杂的色彩 DNA 到您的照片中。',
    'landing.feature.style_cloning.title': '风格克隆',
    'landing.feature.style_cloning.desc': '专有的 Quantum Lens 技术将风格与内容分离，实现完美的美学复制。',
    'landing.feature.comp_analysis.title': '构图分析',
    'landing.feature.comp_analysis.desc': '深度学习算法分解视觉结构，引导您实现完美的构图与平衡。',
    'landing.access_levels': '订阅方案',
    'landing.select_tier': '选择您的权限层级',
    'landing.recommended': '推荐',
    'landing.select_plan': '选择方案',
    'landing.footer': '© 2025 PHOTOSCIENCE INC. 所有系统运行正常。',

    // Pricing
    'pricing.trainee.title': '实习生',
    'pricing.trainee.price': '免费',
    'pricing.trainee.f1': '基础色彩分析',
    'pricing.trainee.f2': '每日 5 次扫描',
    'pricing.trainee.f3': '标准速度',
    'pricing.trainee.f4': '社区访问',
    'pricing.pro.title': '专业许可',
    'pricing.pro.price': '¥98',
    'pricing.pro.period': '/月',
    'pricing.pro.f1': '无限扫描',
    'pricing.pro.f2': '高级矢量示波器',
    'pricing.pro.f3': '4K 导出支持',
    'pricing.pro.f4': '优先处理',
    'pricing.pro.f5': '风格历史记录',
    'pricing.studio.title': '工作室',
    'pricing.studio.price': '¥298',
    'pricing.studio.period': '/月',
    'pricing.studio.f1': 'API 访问',
    'pricing.studio.f2': '团队协作',
    'pricing.studio.f3': '自定义神经模型',
    'pricing.studio.f4': 'Raw 文件支持',
    'pricing.studio.f5': '专属支持',

    
    // Auth
    'auth.login': '登录',
    'auth.register': '申请权限',
    'auth.verify_identity': '身份验证',
    'auth.new_operator': '新操作员注册',
    'auth.email_addr': '电子邮箱',
    'auth.mobile_num': '手机号码',
    'auth.password': '密码',
    'auth.confirm_password': '确认密码',
    'auth.get_code': '获取验证码',
    'auth.use_code': '使用验证码登录',
    'auth.use_pass': '使用密码登录',
    'auth.access_system': '进入系统',
    'auth.establish_id': '建立身份',
    'auth.protocol_v5': '安全连接协议 v5.0',
    'auth.email_code': '邮箱验证码',
    'auth.sms_code': '短信验证码',
    'auth.verifying': '正在验证凭据...',
    'auth.no_account': '还没有权限代码？',
    'auth.has_account': '已经拥有身份？',

    // Modals - Common
    'modal.common.exposure': '曝光',
    'modal.common.contrast': '对比度',
    'modal.common.highlights': '高光',
    'modal.common.shadows': '阴影',
    'modal.common.whites': '白色色阶',
    'modal.common.blacks': '黑色色阶',
    'modal.common.texture': '纹理',
    'modal.common.clarity': '清晰度',
    'modal.common.dehaze': '去朦胧',
    'modal.common.vibrance': '鲜艳度',
    'modal.common.saturation': '饱和度',
    'modal.common.temp': '色温',
    'modal.common.tint': '色调',
    'modal.common.midtones': '中间调',
    'modal.color.reds': '红色',
    'modal.color.yellows': '黄色',
    'modal.color.greens': '绿色',
    'modal.color.cyans': '青色',
    'modal.color.blues': '蓝色',
    'modal.color.magentas': '洋红',
    'modal.color.neutrals': '中性色',
    'modal.common.cyan': '青色',
    'modal.common.magenta': '洋红',
    'modal.common.yellow': '黄色',
    'modal.common.black': '黑色',

    // Simulation Stage
    'simulation.rendering': '渲染中...',
    'simulation.ai_result': 'AI 生成结果',
    'simulation.quantum_grade': '量子分级应用',
    'simulation.diff_heatmap': '差异热力图',
    'simulation.match_score': '匹配得分',
    'simulation.ref_dna': '参考 DNA',
    'simulation.source_input': '源风格输入',
    'simulation.synth_clone': '合成克隆',
    'simulation.final_output': '最终输出',
    'simulation.active_params': '激活参数',
    'simulation.ai_confidence': 'AI 置信度',
    'simulation.param.warmth': '暖意',
    'simulation.param.tint': '色调',
    'simulation.param.shadow': '阴影',
    'simulation.param.highlight': '高光',
    'simulation.download_preset': '下载预设',
    'simulation.download_lut': '下载 LUT',
    'simulation.desc_xmp': '兼容 Adobe Lightroom 和 Camera Raw 的通用 XML 格式。',
    'simulation.desc_lut': '用于视频调色（DaVinci, Premiere, FCPX）的 33 点 3D LUT。',
    'simulation.secure_channel': '安全通道_已建立',
    'simulation.version': '版本 2.4.0_BUILD_88',

    // Modals - Color
    'modal.color.title': '光谱分级',
    'modal.color.strategy': '/// 色彩策略',
    'modal.color.cinematic': '电影级调色',
    'modal.color.hsl': '全息 HSL 矩阵',
    'modal.color.wb': '白平衡',
    'modal.color.wb_target': '白平衡目标',
    'modal.color.tint_cor': '色调校正',
    'modal.color.grading_vectors': '调色向量',
    'modal.color.balance': '平衡',
    'modal.color.spectrum': '光谱矩阵',

    // Modals - Lightroom
    'modal.lr.title': 'Lightroom 开发',
    'modal.lr.protocol': '色彩匹配协议',
    'modal.lr.brief': '任务关键点',
    'modal.lr.signal': '信号监视器',
    'modal.lr.rgb_parade': 'RGB 分量 / 波形',
    'modal.lr.basic': '基础校正',
    'modal.lr.curve': '色调曲线',
    'modal.lr.comp': '构图分析',
    'modal.lr.hsl_mixer': 'HSL / 混色器',
    'modal.lr.grading': '色彩分级',
    'modal.lr.exp_dr': '曝光与动态范围',
    'modal.lr.presence': '质感与氛围',

    // Modals - Photoshop
    'modal.ps.title': 'Photoshop 工作流',
    'modal.ps.hist': '复合直方图',
    'modal.ps.render': '最终渲染输出',
    'modal.ps.layers_active': '活跃图层',
    'modal.ps.stack': '调整堆栈',
    'modal.ps.cr': 'Camera Raw 滤镜',
    'modal.ps.levels': '色阶',
    'modal.ps.curves': '曲线',
    'modal.ps.sel_col': '可选颜色',
    'modal.ps.db': '减淡与加深',
    'modal.ps.atmos': '氛围与颗粒',
    'modal.ps.grain': '颗粒模拟',
    'modal.ps.vol': '体积光氛围',
    
    // Theme Cards - Status
    'status.awaiting': '状态: 等待诊断',
    'status.decrypting': '状态: 解密数据流...',
    'status.ready': '状态: 准备合成',

    // Theme Cards - Diagnosis
    'cards.analysis_bg': '分析',
    'cards.diag_layer': '诊断层',
    'cards.ai_assess': '// AI 视觉评估',
    'cards.review': '综合审查',
    'cards.composition': '构图分析',
    'cards.lighting': '光影分析',
    'cards.aesthetic': '美学评分',
    'cards.geometry': '几何与流线',
    'cards.zone': '区域曝光法',
    'cards.unlock_btn': '生成执行计划',
    'cards.decrypting_vec': '正在解密安全向量...',

    // Theme Cards - Execution
    'cards.exec_bg': '执行',
    'cards.exec_layer': '执行层',
    'cards.tech_proc': '// 技术处理',
    'cards.locked': '已锁定',
    'cards.color': '色彩分级',
    'cards.lightroom': 'LIGHTROOM',
    'cards.photoshop': 'PHOTOSHOP',
    'cards.spectral': '光谱分级',
    'cards.raw_dev': 'RAW 开发',
    'cards.retouch': '修图工作流',
    'cards.init_sim': '初始化模拟',
    'cards.decrypted_msg': '执行向量已解密',

    // Photo Upload Zone
    'upload.wavelength': '波长',
    'upload.flux': '光谱通量: 已检测',
    
    // Main App - Header
    'nav.upload': '上传',
    'nav.analysis': '风格分析',
    'nav.simulation': '开启模拟',
    'nav.unlock_sim': '完成 AI 诊断以解锁模拟阶段',
    
    // Upload Stage
    'stage.upload.title': 'QUANTUM LENS',
    'stage.upload.subtitle': 'AI神经网络风格迁移系统',
    'stage.upload.ref_label': '风格参考图',
    'stage.upload.target_label': '目标原图',
    'stage.upload.btn_analyze': '初始化分析',
    'stage.upload.btn_analyzing': '张量处理中...',
    
    // Analysis Stage
    'stage.analysis.title': '分析结果',
    'stage.analysis.simulate': '运行模拟',

    // Simulation Stage
    'simulation.title': '模拟渲染',
    'simulation.subtitle.gen': 'Gemini Flash 生成',
    'simulation.subtitle.opt': '实时光学引擎',
    'simulation.processing': '神经风格迁移处理中...',
    'simulation.engine_ready': '引擎就绪',
    'simulation.gpu_accel': 'GPU 加速',
    'simulation.split_view': '分屏视图',
    'simulation.diff_map': '差异热图',
    'simulation.style_match': '风格匹配',
    'simulation.rerun': '重运行模拟',
    'simulation.download': '下载资产',
    'simulation.export_panel': '数据导出控制台',
    'simulation.preset_xmp': 'Lightroom 预设 (.XMP)',
    'simulation.lut_cube': '3D LUT 查找表 (.CUBE)',
    'simulation.generating': '生成中...',
    'simulation.download_ready': '下载就绪',
    'simulation.close': '关闭控制台',

    // Visual Analysis Dashboard
    'vad.tools': '分析工具',
    'vad.scopes': '专业级示波器',
    'vad.histogram': '亮度直方图',
    'vad.vectorscope': '色彩雷达',
    'vad.ai_diagnosis': 'AI 诊断',
    'vad.overlays': '叠加层',
    'vad.false_color_desc': '伪色将亮度映射为颜色，帮助您无需猜测即可判断曝光。',
    'vad.show_map': '显示曝光图',
    'vad.hide_map': '隐藏曝光图',
    'vad.luma_dist': '亮度分布 (Y)',
    'vad.luma_range': '0 (黑) — 255 (白)',
    'vad.hist_desc': '显示图像中暗部（左）、中间调（中）或亮部（右）的比例。',
    'vad.chroma_vec': '色度矢量 (UV)',
    'vad.chroma_range': '中心=灰, 边缘=鲜艳',
    'vad.vector_desc': '“色彩指南针”：方向表示色相，距中心的距离表示饱和度。',
    'vad.skin_tone': '肤色应落在粉红线上。',
    'vad.skin_tone_title': '肤色指示线说明',
    'vad.skin_tone_subtitle': 'SKIN TONE LINE',
    'vad.skin_tone_location': '位置',
    'vad.skin_tone_location_desc': '色彩雷达 11 点钟方向（约 -33°）',
    'vad.skin_tone_meaning': '含义',
    'vad.skin_tone_meaning_desc': '标准肤色的色相与饱和度参考范围',
    'vad.skin_tone_guide': '判断指南',
    'vad.skin_tone_accurate': '落在线上：肤色准确',
    'vad.skin_tone_yellow': '偏右：偏黄（色温过暖）',
    'vad.skin_tone_red': '偏左：偏红（饱和过高）',
    'vad.skin_tone_green': '偏下：偏绿（白平衡偏冷）',
    
    // User Profile
    'profile.title': '操作员档案',
    'profile.id': '操作员 ID',
    'profile.clearance': '权限等级',
    'profile.credits': '算力点数',
    'profile.history': '操作记录',
    'profile.logout': '断开连接',
    'profile.operator': '操作员',
    'profile.settings_console': '设置控制台',
    'profile.change_avatar': '更换头像',
    'profile.reset_key': '重置密钥',
    'profile.generating': '生成中...',
    'profile.username': '用户名',
    'profile.email': '电子邮箱',
    'profile.password': '密码',
    'profile.update': '更新',
    'profile.alipay_binding': '支付宝绑定',
    'profile.secure_quick': '安全快捷支付集成',
    'profile.connected': '已连接',
    'profile.tab_identity': '身份',
    'profile.tab_plan': '方案与用量',
    'profile.tab_billing': '账单',
    'profile.tab_tasks': '任务日志',
    'profile.tab_network': '网络',
    'profile.tab_protocols': '协议',
    
    // Subscription
    'subscription.current_plan': '当前方案',
    'subscription.gpu_cluster': '高速 GPU 集群',
    'subscription.load': '负载',
    'subscription.used_credits': '已用点数',
    'subscription.total_limit': '总额度',
    'subscription.renewal': '续期',
    'subscription.days': '天',
    'subscription.mo': '/月',
    'subscription.tier_free': '免费版',
    'subscription.tier_pro': '专业版',
    'subscription.tier_enterprise': '企业版',
    'subscription.plan_selection': '方案选择',
    'subscription.switching_to': '正在切换至 {tier}...',
    
    // Share
    'share.title': '神经网络同步',
    'share.desc': '启用模拟结果的公共访问权限。为全球学习模型做出贡献。',
    'share.auto_publish': '自动发布',
    'share.sync_enabled': '同步已启用',
    'share.connected_hive': '您已连接到蜂巢网络。',

    // Billing & Payment
    'billing.payment_methods': '支付方式',
    'billing.add_method': '添加支付方式',
    'billing.edit_card': '编辑卡片信息',
    'billing.card_number': '卡号',
    'billing.cardholder': '持卡人姓名',
    'billing.expiry': '过期日期',
    'billing.cvv': '安全码 (CVV)',
    'billing.set_default': '设为默认',
    'billing.remove': '移除',
    'billing.scan_qr': '扫描二维码绑定',
    'billing.connect_paypal': '连接 PayPal 账户',
    'billing.bind_success': '支付方式绑定成功',
    'billing.update_success': '支付信息已更新',
    'billing.no_methods': '暂无支付方式。',
    'billing.primary': '主支付',
    'billing.scan_instruction': '请打开 App 扫描下方二维码。',
    'billing.simulating_redirect': '正在模拟安全网关跳转...',
    'billing.simulating_scan': '等待支付提供商确认...',
    'billing.tab_card': '信用卡',
    'billing.tab_alipay': '支付宝/微信',
    'billing.tab_paypal': 'PayPal',
    'billing.exp_label': '有效期',
    'billing.click_scan': '点击模拟扫描',
    'billing.connecting': '正在连接...',
    'billing.update_btn': '更新卡片',
    'billing.placeholder_name': '持卡人姓名',
    'billing.paypal_title': 'PayPal 安全连接',
    'billing.paypal_desc': '您将被重定向到 PayPal 以授权绑定协议。',

    // Zone System Visualizer
    'zone.system.title': '安塞尔·亚当斯区域曝光法',
    'zone.system.subtitle': '亮度映射',
    'zone.face': '肤色',
    'zone.pure_black': '纯黑',
    'zone.middle_grey': '中灰',
    'zone.pure_white': '纯白',
    'zone.desc.0': '无细节',
    'zone.desc.1': '微弱色调',
    'zone.desc.2': '最暗纹理',
    'zone.desc.3': '平均阴影细节',
    'zone.desc.4': '风景阴影 / 深肤色',
    'zone.desc.5': '18% 灰 / 柯达灰卡',
    'zone.desc.6': '白人/亚洲人肤色',
    'zone.desc.7': '浅色皮肤 / 浅色石材',
    'zone.desc.8': '带细节高光',
    'zone.desc.9': '近乎白色',
    'zone.desc.10': '镜面光源',
    'zone.name.0': '纯黑',
    'zone.name.1': '近黑',
    'zone.name.2': '纹理黑',
    'zone.name.3': '阴影',
    'zone.name.4': '深肤色',
    'zone.name.5': '中灰',
    'zone.name.6': '平均肤色',
    'zone.name.7': '浅肤色',
    'zone.name.8': '白色',
    'zone.name.9': '亮白',
    'zone.name.10': '纸白',

    // AI Analysis Panel
    'ai.monitor.title': '视觉皮层监视器',
    'ai.live_signal': '实时信号',
    'ai.idle_desc': '曝光数据实时更新。要解码风格 DNA、色彩和谐度和构图，请启动神经引擎。',
    'ai.btn_scan': '启动深度扫描',
    'ai.analyzing': '正在分析视觉皮层',
    'ai.step.hist': '提取直方图数据...',
    'ai.step.color': '映射颜色向量...',
    'ai.step.style': '生成风格嵌入...',
    'ai.step.report': '生成最终报告...',
    'ai.report.title': 'AI 诊断报告',
    'ai.token': '令牌',
    'ai.tab.overview': '概览',
    'ai.tab.color': '色彩 DNA',
    'ai.tab.lr': 'Lightroom',
    'ai.tab.ps': 'Photoshop',
    'ai.sec.style': '01. 风格档案',
    'ai.sec.comp': '02. 构图与结构',
    'ai.sec.zone': '03. 区域曝光系统',
    'ai.sec.harmony': '04. 色彩和谐引擎',
    'ai.sec.lr': '05. Lightroom 协议',
    'ai.sec.ps': '06. Photoshop 堆栈',
    'ai.comp.struct': '结构分析',
    'ai.comp.weight': '主体权重',
    'ai.color.grading': '电影级分级',
    'ai.color.hsl': '全息 HSL 矩阵',
    'ai.color.wb': '白平衡',
    'ai.color.style_key': '风格密钥',

    // Color Grade Wheel
    'color.grade.engine': '分级引擎',
    'color.grade.awaiting': '等待矢量输入。悬停滚轮以查看色调分离逻辑...',
    'color.grade.pushing': '将 {label} 推向色相 {hue}°，饱和度 {sat}%。',

    // HSL Visualizer
    'hsl.matrix.title': '全息光谱矩阵',
    'hsl.matrix.sat': '饱和度',
    'hsl.matrix.lum': '明度',
    'hsl.matrix.engine': '色彩矩阵',
    'hsl.matrix.idle': '选择频段以进行调制分析...',
    'hsl.reason.no_dev': '与源基线无显著偏差。',
    'hsl.reason.adjust': '调整',
    'hsl.reason.match': '以匹配目标调色板密度。',
    'hsl.reason.hue': '色相偏移',
    'hsl.reason.sat': '饱和度',
    'hsl.reason.lum': '亮度',
    'hsl.channel.red': '红色',
    'hsl.channel.orange': '橙色',
    'hsl.channel.yellow': '黄色',
    'hsl.channel.green': '绿色',
    'hsl.channel.aqua': '青色',
    'hsl.channel.blue': '蓝色',
    'hsl.channel.purple': '紫色',
    'hsl.channel.magenta': '洋红',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('zh');
  const [isTransitioning, setIsTransitioning] = useState(false);
  const [nextLanguage, setNextLanguage] = useState<Language | null>(null);

  const setLanguage = (lang: Language) => {
    if (lang === language) return;
    setNextLanguage(lang);
    setIsTransitioning(true);
  };

  const handleTransitionComplete = () => {
    if (nextLanguage) {
      setLanguageState(nextLanguage);
      setNextLanguage(null);
    }
    setIsTransitioning(false);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <AnimatePresence>
        {isTransitioning && (
          <LanguageTransition 
            from={language} 
            to={nextLanguage || 'en'} 
            onComplete={handleTransitionComplete} 
          />
        )}
      </AnimatePresence>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
